using System.Text;

namespace Umcp.ToolGen;

internal static class Emit
{
    const string Header =
        "// <auto-generated>\n" +
        "//     Generated by umcp-toolgen from the [UnityTool] methods in\n" +
        "//     unity/com.umcp.agent/Editor/. Do not edit by hand — edit the tool and\n" +
        "//     re-run `dotnet run --project src/Umcp.ToolGen`.\n" +
        "// </auto-generated>\n";

    public static string UnityDispatch(List<ToolModel> tools)
    {
        var sb = new StringBuilder(Header);
        sb.Append("""

            using System.Collections.Generic;
            using Newtonsoft.Json.Linq;

            namespace Umcp.Agent
            {
                internal static class ToolDispatch
                {
                    public static readonly string[] Ids =
                    {

            """);

        foreach (var t in tools) sb.Append("            ").Append(Json.CsStr(t.Id)).Append(",\n");

        sb.Append("""
                    };

                    static readonly Dictionary<string, ToolMeta> _meta = new Dictionary<string, ToolMeta>
                    {

            """);

        foreach (var t in tools)
        {
            sb.Append("            { ").Append(Json.CsStr(t.Id)).Append(", new ToolMeta { Id = ").Append(Json.CsStr(t.Id))
              .Append(", Skill = ").Append(Json.CsStr(t.Skill))
              .Append(", Summary = ").Append(Json.CsStr(t.Summary))
              .Append(", Mutating = ").Append(t.Mutating ? "true" : "false")
              .Append(", Retry = ").Append(Json.CsStr(t.Retry))
              .Append(", Cost = ").Append(Json.CsStr(t.Cost))
              .Append(", Undo = ").Append(Json.CsStr(t.Undo))
              .Append(", NoUndoReason = ").Append(Json.CsStr(t.NoUndoReason))
              .Append(" } },\n");
        }

        sb.Append("""
                    };

                    public static ToolMeta Meta(string id)
                    {
                        ToolMeta m;
                        return _meta.TryGetValue(id, out m) ? m : null;
                    }

                    /// <summary>Dispatch by id. No hand-written switch: this file is generated.</summary>
                    public static object Invoke(string id, JObject a)
                    {
                        switch (id)
                        {

            """);

        foreach (var t in tools)
        {
            sb.Append("                case ").Append(Json.CsStr(t.Id)).Append(":\n");
            sb.Append("                    return ").Append(t.Owner).Append('.').Append(t.Method).Append('(');
            sb.Append(string.Join(", ", t.Params.Select(p => p.Binder())));
            sb.Append(");\n");
        }

        sb.Append("""
                            default:
                                throw new UmcpToolException("E_TOOL_NOT_FOUND", "No tool named '" + id + "'.", "tool", id);
                        }
                    }

                    /// <summary>
                    /// Run a tool's argument binders and throw exactly what a real call would
                    /// throw, without calling the tool. This is what makes dryRun a validation
                    /// rather than a promise: the same generated binders, the same errors.
                    /// </summary>
                    public static void Validate(string id, JObject a)
                    {
                        switch (id)
                        {

            """);

        foreach (var t in tools)
        {
            // Each case gets its own scope: two tools that share a parameter name would
            // otherwise declare the same local twice in the switch's shared scope.
            sb.Append("                case ").Append(Json.CsStr(t.Id)).Append(":\n                {\n");
            foreach (var p in t.Params)
                sb.Append("                    ").Append(p.BindDiscard()).Append(";\n");
            sb.Append("                    return;\n                }\n");
        }

        sb.Append("""
                            default:
                                throw new UmcpToolException("E_TOOL_NOT_FOUND", "No tool named '" + id + "'.", "tool", id);
                        }
                    }
                }
            }

            """);

        return sb.ToString();
    }

    public static string DaemonCatalog(List<ToolModel> tools)
    {
        var sb = new StringBuilder(Header);
        sb.Append("""

            #nullable enable

            namespace Umcp.Daemon.Generated;

            /// <summary>One catalog entry per Unity-side tool, generated from the same [UnityTool]
            /// attributes the dispatch table is generated from.</summary>
            public sealed record ToolEntry(
                string Id,
                string Skill,
                string Summary,
                bool Mutating,
                string Retry,
                string Cost,
                string? Undo,
                string? NoUndoReason,
                string InputSchema,
                string[] Examples);

            public static class ToolCatalog
            {
                public static readonly ToolEntry[] All =
                {

            """);

        foreach (var t in tools)
        {
            sb.Append("        new(")
              .Append(Json.CsStr(t.Id)).Append(", ")
              .Append(Json.CsStr(t.Skill)).Append(", ")
              .Append(Json.CsStr(t.Summary)).Append(", ")
              .Append(t.Mutating ? "true" : "false").Append(", ")
              .Append(Json.CsStr(t.Retry)).Append(", ")
              .Append(Json.CsStr(t.Cost)).Append(", ")
              .Append(Json.CsStr(t.Undo)).Append(", ")
              .Append(Json.CsStr(t.NoUndoReason)).Append(", ")
              .Append(Json.CsStr(t.InputSchema())).Append(", ")
              .Append("new[]{ ")
              .Append(string.Join(", ", t.Examples.Select(Json.CsStr)))
              .Append(" }),\n");
        }

        sb.Append("""
                };

                public static readonly System.Collections.Generic.Dictionary<string, ToolEntry> ById =
                    System.Linq.Enumerable.ToDictionary(All, e => e.Id);
            }

            """);

        return sb.ToString();
    }

    public static string Docs(List<ToolModel> tools)
    {
        var sb = new StringBuilder();
        sb.Append("<!-- Generated by umcp-toolgen. Do not edit by hand. -->\n\n");
        sb.Append("# Tool reference\n\n");
        sb.Append($"{tools.Count} tools, generated from the `[UnityTool]` attributes in `unity/com.umcp.agent/Editor/`.\n\n");

        foreach (var group in tools.GroupBy(t => t.Skill).OrderBy(g => g.Key, StringComparer.Ordinal))
        {
            sb.Append($"## {group.Key}\n\n");
            sb.Append("| Tool | Mutating | Undo | Summary |\n|---|---|---|---|\n");
            foreach (var t in group.OrderBy(t => t.Id, StringComparer.Ordinal))
            {
                var undo = t.Mutating ? (t.Undo ?? "— *" + (t.NoUndoReason ?? "no undo") + "*") : "n/a";
                sb.Append($"| `{t.Id}` | {(t.Mutating ? "yes" : "no")} | {undo} | {t.Summary} |\n");
            }
            sb.Append('\n');

            foreach (var t in group.OrderBy(t => t.Id, StringComparer.Ordinal))
            {
                sb.Append($"### `{t.Id}`\n\n{t.Summary}\n\n");
                if (t.Params.Count > 0)
                {
                    sb.Append("| Parameter | Type | Required | Default | Description |\n|---|---|---|---|---|\n");
                    foreach (var p in t.Params)
                        sb.Append($"| `{p.Name}` | `{p.CsType}` | {(p.Required ? "yes" : "no")} | {(p.Default is null ? "—" : "`" + p.Default + "`")} | {p.Doc ?? ""} |\n");
                    sb.Append('\n');
                }
                foreach (var ex in t.Examples)
                    sb.Append("```json\n").Append(ex).Append("\n```\n\n");
            }
        }
        return sb.ToString();
    }
}
